### ISSUE TITLE
Unable to build game

### ISSUE THREAD

**Issue by AndroidKitKat** [sambattalio/space_invaders#1]
Hi i'm using Kali linux and i can't build the game thank

me@dino:~/src/space_invaders$ make
g++ -c player.cpp -std=c++11 -o player.o
g++ -c invader.cpp -std=c++11 -o invader.o
g++ -c laser.cpp -std=c++11 -o laser.o
g++ -c invaderClump.cpp -std=c++11 -o invaderClump.o
g++ -c button.cpp -std=c++11 -o button.o
g++ -c project.cpp -std=c++11 -o project.o
g++ player.o invader.o laser.o invaderClump.o button.o project.o gfx2.o -lX11 -std=c++11 -o spaceyboi
/usr/bin/ld: gfx2.o: relocation R_X86_64_PC32 against symbol `XOpenDisplay' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make: *** [Makefile:12: spaceyboi] Error 1

**Comment by AndroidKitKat** [comment]
yeah this is urgent i can't play

**Comment by AndroidKitKat** [comment]
help please

**Comment by sambattalio** [comment]
Yea this is because i don't have the library file on here. Im gonna say just enjoy the gif

**Comment by AndroidKitKat** [comment]
ok i like gif
